# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Order(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, order_number: str=None, order_date: str=None, customer_id: int=None, order_lines: List[OrderLine]=None):  # noqa: E501
        """Order - a model defined in Swagger

        :param id: The id of this Order.  # noqa: E501
        :type id: int
        :param order_number: The order_number of this Order.  # noqa: E501
        :type order_number: str
        :param order_date: The order_date of this Order.  # noqa: E501
        :type order_date: str
        :param customer_id: The customer_id of this Order.  # noqa: E501
        :type customer_id: int
        :param order_lines: The order_lines of this Order.  # noqa: E501
        :type order_lines: List[OrderLine]
        """
        self.swagger_types = {
            'id': int,
            'order_number': str,
            'order_date': str,
            'customer_id': int,
            'order_lines': List[OrderLine]
        }

        self.attribute_map = {
            'id': 'id',
            'order_number': 'order_number',
            'order_date': 'orderDate',
            'customer_id': 'customerId',
            'order_lines': 'orderLines'
        }

        self._id = id
        self._order_number = order_number
        self._order_date = order_date
        self._customer_id = customer_id
        self._order_lines = order_lines

    @classmethod
    def from_dict(cls, dikt) -> 'Order':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Order of this Order.  # noqa: E501
        :rtype: Order
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Order.


        :return: The id of this Order.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Order.


        :param id: The id of this Order.
        :type id: int
        """

        self._id = id

    @property
    def order_number(self) -> str:
        """Gets the order_number of this Order.


        :return: The order_number of this Order.
        :rtype: str
        """
        return self._order_number

    @order_number.setter
    def order_number(self, order_number: str):
        """Sets the order_number of this Order.


        :param order_number: The order_number of this Order.
        :type order_number: str
        """

        self._order_number = order_number

    @property
    def order_date(self) -> str:
        """Gets the order_date of this Order.


        :return: The order_date of this Order.
        :rtype: str
        """
        return self._order_date

    @order_date.setter
    def order_date(self, order_date: str):
        """Sets the order_date of this Order.


        :param order_date: The order_date of this Order.
        :type order_date: str
        """

        self._order_date = order_date

    @property
    def customer_id(self) -> int:
        """Gets the customer_id of this Order.


        :return: The customer_id of this Order.
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: int):
        """Sets the customer_id of this Order.


        :param customer_id: The customer_id of this Order.
        :type customer_id: int
        """

        self._customer_id = customer_id

    @property
    def order_lines(self) -> List[OrderLine]:
        """Gets the order_lines of this Order.


        :return: The order_lines of this Order.
        :rtype: List[OrderLine]
        """
        return self._order_lines

    @order_lines.setter
    def order_lines(self, order_lines: List[OrderLine]):
        """Sets the order_lines of this Order.


        :param order_lines: The order_lines of this Order.
        :type order_lines: List[OrderLine]
        """

        self._order_lines = order_lines
